version: "3.8"
services:
    
  vas-box:
    build: ./box
    container_name: vas-box
    restart: always
    environment:
      APP_PORT: "${APP_PORT}"
      MONGODB_URL: ${MONGO_URI}
    volumes:
      - $PWD/STORAGE/build:/app/src/uploads
    networks:
      - nonicoms-net     
networks:
  nonicoms-net:
    external: true 
